apiVersion: v1
kind: Service
metadata:
  name: prod
  namespace: mdservice2
spec:
  selector:
    service: mdservice2-se-prod
  externalIPs: []
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges: []
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer
