apiVersion: v1
kind: Service
metadata:
  name: stage
  namespace: mdservice2
spec:
  selector:
    mdservice2-service: stage
  externalIPs: []
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges: []
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer
