apiVersion: v1
kind: Service
metadata:
  name: stage
  namespace: mdservice2
spec:
  externalIPs: []
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges: []
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mdservice2-stage
    load-balancer-mdservice2-stage: true
  sessionAffinity: None
  type: LoadBalancer
