apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-canary
  labels:
    app: mdservice2-prod-canary
  namespace: mdservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdservice2-prod-canary
  template:
    metadata:
      labels:
        app: mdservice2-prod-canary
    spec:
      containers:
      - image: gcr.io/spinnaker-1022/mdservice2
        name: mdservice2-prod-canary
        ports:
        - containerPort: 80

