apiVersion: "v1"
kind: "Service"
metadata:
  name: "mdservice2-stage"
  namespace: mdservice2
spec:
  externalIPs: []
  externalTrafficPolicy: "Cluster"
  loadBalancerSourceRanges: []
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 80
  selector:
    load-balancer-mdservice2-stage: "true"
  sessionAffinity: "None"
  type: "LoadBalancer"
